"""
Save/Load System Module Template for Godot 4.3+

This module is auto-generated by the Coder agent when the user selects "Saving: Yes" in the wizard (Step 7).
Implements automatic save/load functionality as specified in Section 8.

Features:
- JSON-based save file storage
- Player state serialization (position, health, inventory)
- Quest state serialization
- Dialogue flags serialization
- World state serialization (opened doors, triggered events, destroyed objects)
- Play time tracking
- Graceful error handling (corrupted save fallback)
"""

extends Node
class_name SaveSystem

const SAVE_PATH := "user://kotodama_save.json"
const VERSION := 1

# Signals
signal save_started()
signal save_completed(success: bool)
signal load_started()
signal load_completed(success: bool)
signal save_not_found()

# References (set by game manager)
var player_ref: Node2D = null
var quest_manager_ref: Node = null
var dialogue_manager_ref: Node = null
var inventory_manager_ref: Node = null
var world_state_ref: Node = null

# Play time tracking
var play_time_seconds: float = 0.0
var _play_time_timer: Timer = null


func _ready() -> void:
	# Start play time tracking
	_play_time_timer = Timer.new()
	_play_time_timer.wait_time = 1.0
	_play_time_timer.autostart = true
	_play_time_timer.timeout.connect(_on_play_time_tick)
	add_child(_play_time_timer)


func _on_play_time_tick() -> void:
	play_time_seconds += 1.0


func set_references(player: Node2D, quests: Node, dialogues: Node, inventory: Node, world: Node) -> void:
	"""Set references to game managers."""
	player_ref = player
	quest_manager_ref = quests
	dialogue_manager_ref = dialogues
	inventory_manager_ref = inventory
	world_state_ref = world


func save_game() -> bool:
	"""
	Save current game state to JSON file.
	Returns true on success, false on failure.
	"""
	save_started.emit()
	
	var state := _build_save_data()
	
	var json_string := JSON.stringify(state, "\t")
	
	var file := FileAccess.open(SAVE_PATH, FileAccess.WRITE)
	if file == null:
		push_error("SaveSystem: Failed to open save file for writing")
		save_completed.emit(false)
		return false
	
	file.store_string(json_string)
	file.close()
	
	print("SaveSystem: Game saved successfully")
	save_completed.emit(true)
	return true


func load_game() -> bool:
	"""
	Load game state from JSON file.
	Returns true on success, false on failure or corruption.
	"""
	load_started.emit()
	
	if not has_save():
		print("SaveSystem: No save file found")
		save_not_found.emit()
		load_completed.emit(false)
		return false
	
	var file := FileAccess.open(SAVE_PATH, FileAccess.READ)
	if file == null:
		push_error("SaveSystem: Failed to open save file for reading")
		load_completed.emit(false)
		return false
	
	var json_string := file.get_as_text()
	file.close()
	
	# Parse JSON with error handling
	var json := JSON.new()
	var parse_result := json.parse(json_string)
	if parse_result != OK:
		push_error("SaveSystem: Corrupted save file (JSON parse error)")
		# Graceful fallback: delete corrupted save
		delete_save()
		load_completed.emit(false)
		return false
	
	var state: Dictionary = json.data
	
	# Validate version
	var saved_version: int = state.get("version", 0)
	if saved_version != VERSION:
		push_warning("SaveSystem: Version mismatch (saved: %d, current: %d)" % [saved_version, VERSION])
		# Could implement migration logic here
	
	# Restore state
	var success := _restore_state(state)
	
	if success:
		print("SaveSystem: Game loaded successfully")
	else:
		push_error("SaveSystem: Failed to restore state, starting new game")
		# Delete corrupted save
		delete_save()
	
	load_completed.emit(success)
	return success


func has_save() -> bool:
	"""Check if a save file exists."""
	return FileAccess.file_exists(SAVE_PATH)


func delete_save() -> void:
	"""Delete the save file if it exists."""
	if has_save():
		DirAccess.remove_absolute(SAVE_PATH)
		print("SaveSystem: Save file deleted")


func get_save_timestamp() -> String:
	"""Get the timestamp of the last save, or empty string if no save exists."""
	if not has_save():
		return ""
	
	var file := FileAccess.open(SAVE_PATH, FileAccess.READ)
	if file == null:
		return ""
	
	var json_string := file.get_as_text()
	file.close()
	
	var json := JSON.new()
	if json.parse(json_string) != OK:
		return ""
	
	var state: Dictionary = json.data
	return state.get("timestamp", "")


func _build_save_data() -> Dictionary:
	"""Build the save data dictionary from current game state."""
	var state := {
		"version": VERSION,
		"timestamp": Time.get_datetime_string_from_system(),
		"player": _serialize_player(),
		"quests": _serialize_quests() if quest_manager_ref else {},
		"dialogue_flags": _serialize_dialogues() if dialogue_manager_ref else {},
		"inventory": _serialize_inventory() if inventory_manager_ref else {},
		"world_state": _serialize_world_state() if world_state_ref else {},
		"play_time_seconds": play_time_seconds,
	}
	return state


func _serialize_player() -> Dictionary:
	"""Serialize player state."""
	if player_ref == null:
		return {}
	
	return {
		"position": [player_ref.global_position.x, player_ref.global_position.y],
		"health": player_ref.get("health", 100) if player_ref.has_meta("health") else 100,
		"flags": _get_player_flags(),
	}


func _get_player_flags() -> Dictionary:
	"""Get player-specific flags/variables."""
	var flags := {}
	if player_ref and player_ref.has_meta("flags"):
		flags = player_ref.get_meta("flags")
	return flags


func _serialize_quests() -> Dictionary:
	"""Serialize quest manager state."""
	if quest_manager_ref == null:
		return {}
	
	# Call serialize method if available
	if quest_manager_ref.has_method("serialize"):
		return quest_manager_ref.serialize()
	
	# Fallback: try to get active/completed quests
	return {
		"active_quests": quest_manager_ref.get("active_quests", []) if quest_manager_ref.has_meta("active_quests") else [],
		"completed_quests": quest_manager_ref.get("completed_quests", []) if quest_manager_ref.has_meta("completed_quests") else [],
		"quest_flags": quest_manager_ref.get("quest_flags", {}) if quest_manager_ref.has_meta("quest_flags") else {},
	}


func _serialize_dialogues() -> Dictionary:
	"""Serialize dialogue manager state."""
	if dialogue_manager_ref == null:
		return {}
	
	# Call get_flags method if available (per spec Section 8.3)
	if dialogue_manager_ref.has_method("get_flags"):
		return dialogue_manager_ref.get_flags()
	
	# Fallback
	return dialogue_manager_ref.get("flags", {}) if dialogue_manager_ref.has_meta("flags") else {}


func _serialize_inventory() -> Dictionary:
	"""Serialize inventory manager state."""
	if inventory_manager_ref == null:
		return {}
	
	# Call serialize method if available (per spec Section 8.3)
	if inventory_manager_ref.has_method("serialize"):
		return inventory_manager_ref.serialize()
	
	# Fallback
	return {
		"items": inventory_manager_ref.get("items", []) if inventory_manager_ref.has_meta("items") else [],
		"equipment": inventory_manager_ref.get("equipment", {}) if inventory_manager_ref.has_meta("equipment") else {},
	}


func _serialize_world_state() -> Dictionary:
	"""Serialize world state (opened doors, triggered events, destroyed objects)."""
	if world_state_ref == null:
		return {}
	
	# Call serialize method if available (per spec Section 8.3)
	if world_state_ref.has_method("serialize"):
		return world_state_ref.serialize()
	
	# Fallback
	return {
		"opened_doors": world_state_ref.get("opened_doors", []) if world_state_ref.has_meta("opened_doors") else [],
		"triggered_events": world_state_ref.get("triggered_events", []) if world_state_ref.has_meta("triggered_events") else [],
		"destroyed_objects": world_state_ref.get("destroyed_objects", []) if world_state_ref.has_meta("destroyed_objects") else [],
	}


func _restore_state(state: Dictionary) -> bool:
	"""Restore game state from save data."""
	if state.is_empty():
		return false
	
	# Restore player
	var player_data: Dictionary = state.get("player", {})
	_restore_player(player_data)
	
	# Restore quests
	var quests_data: Dictionary = state.get("quests", {})
	_restore_quests(quests_data)
	
	# Restore dialogues
	var dialogues_data: Dictionary = state.get("dialogue_flags", {})
	_restore_dialogues(dialogues_data)
	
	# Restore inventory
	var inventory_data: Dictionary = state.get("inventory", {})
	_restore_inventory(inventory_data)
	
	# Restore world state
	var world_data: Dictionary = state.get("world_state", {})
	_restore_world_state(world_data)
	
	# Restore play time
	play_time_seconds = float(state.get("play_time_seconds", 0.0))
	
	return true


func _restore_player(data: Dictionary) -> void:
	"""Restore player state."""
	if player_ref == null or data.is_empty():
		return
	
	# Restore position
	if "position" in data:
		var pos: Array = data["position"]
		if pos.size() == 2:
			player_ref.global_position = Vector2(pos[0], pos[1])
	
	# Restore health
	if "health" in data and player_ref.has_meta("health"):
		player_ref.set_meta("health", data["health"])
	
	# Restore flags
	if "flags" in data:
		for key in data["flags"]:
			player_ref.set_meta(key, data["flags"][key])


func _restore_quests(data: Dictionary) -> void:
	"""Restore quest manager state."""
	if quest_manager_ref == null or data.is_empty():
		return
	
	# Call deserialize method if available
	if quest_manager_ref.has_method("deserialize"):
		quest_manager_ref.deserialize(data)
		return
	
	# Fallback: set meta values
	if "active_quests" in data:
		quest_manager_ref.set_meta("active_quests", data["active_quests"])
	if "completed_quests" in data:
		quest_manager_ref.set_meta("completed_quests", data["completed_quests"])
	if "quest_flags" in data:
		quest_manager_ref.set_meta("quest_flags", data["quest_flags"])


func _restore_dialogues(data: Dictionary) -> void:
	"""Restore dialogue manager state."""
	if dialogue_manager_ref == null or data.is_empty():
		return
	
	# Call set_flags method if available
	if dialogue_manager_ref.has_method("set_flags"):
		dialogue_manager_ref.set_flags(data)
		return
	
	# Fallback
	dialogue_manager_ref.set_meta("flags", data)


func _restore_inventory(data: Dictionary) -> void:
	"""Restore inventory manager state."""
	if inventory_manager_ref == null or data.is_empty():
		return
	
	# Call deserialize method if available
	if inventory_manager_ref.has_method("deserialize"):
		inventory_manager_ref.deserialize(data)
		return
	
	# Fallback: set meta values
	if "items" in data:
		inventory_manager_ref.set_meta("items", data["items"])
	if "equipment" in data:
		inventory_manager_ref.set_meta("equipment", data["equipment"])


func _restore_world_state(data: Dictionary) -> void:
	"""Restore world state."""
	if world_state_ref == null or data.is_empty():
		return
	
	# Call deserialize method if available
	if world_state_ref.has_method("deserialize"):
		world_state_ref.deserialize(data)
		return
	
	# Fallback: set meta values
	if "opened_doors" in data:
		world_state_ref.set_meta("opened_doors", data["opened_doors"])
		# Actually open the doors
		for door_id in data["opened_doors"]:
			_open_door_by_id(door_id)
	
	if "triggered_events" in data:
		world_state_ref.set_meta("triggered_events", data["triggered_events"])
	
	if "destroyed_objects" in data:
		world_state_ref.set_meta("destroyed_objects", data["destroyed_objects"])


func _open_door_by_id(door_id: String) -> void:
	"""Find and open a door by its ID."""
	var door = get_node_or_null("/root/Game/" + door_id)
	if door == null:
		# Try to find by group
		var doors = get_tree().get_nodes_in_group("door")
		for d in doors:
			if d.name == door_id or d.get_meta("door_id", "") == door_id:
				door = d
				break
	
	if door and door.has_method("open"):
		door.open()
